#server:
#    port: 8080
#    context-path: #/liuzh/

logging:
    level:
        tk.mybatis: DEBUG
spring:
    mvc:
        view:
            prefix: /WEB-INF/view/
            suffix: .jsp
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC&useSSL=false
        username: root
        password: root
        # 使用druid数据源

        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      host: 10.0.1.98
      # password: root
      port: 6379
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss

